### ISSUE TITLE
How to calculate gene haplotypes/major gene haplotypes?

### ISSUE THREAD

**Issue by caixu0518** [mb47/barleyvariomics#1]
Hi,

I'm currently learning about your interesting research published in TPJ. It provides a new insigts into the evolution of pericentromeric regions during the domestication of Braly. 

When I read the Figure 4, i was very confused how to determine the (major) haplotypes of each gene. I found the gene haplotype count for some genes reach ~100. 

I want to know how you determine the gene haplotypes and major haplotypes. It seems this part is not include in your codes. 

Best,
Xu

**Comment by mb47** [comment]
Hi Xu,

you are right, we had forgotten to include these scripts. I have now added a directory called 'haplotypes' to the code folder. It includes all the scripts that were used for the haplotype analysis. Unfortunately the analysis was done by a colleague who has now moved on, so I am afraid I can't provide any advice on how to use these scripts, sorry.

Best regards, Micha

**Comment by caixu0518** [comment]
Many thanks for your kind feedback.

Best,
Xu
